name: BlissInterface
version: "0.21"
date: 2019-10-08
description: |
    Low level interface to the bliss graph automorphism tool

authors:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

maintainers:
    - name: Gábor P. Nagy
      url: https://algebra.math.bme.hu/nagy-gabor

GAP: ">= 4.9"

www: https://gap-packages.github.io/BlissInterface/
readme: README.md
packageinfo: https://gap-packages.github.io/BlissInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/BlissInterface/releases/download/v0.21/BlissInterface-0.21.tar.gz
    - name: .zip
      url: https://github.com/gap-packages/BlissInterface/releases/download/v0.21/BlissInterface-0.21-win.zip

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Nag19</span>]   <b class='BibAuthor'>Nagy, G. P.</b>,
     <i class='BibTitle'>BlissInterface, Low level interface to the bliss graph automorphism tool,
             Version 0.21</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/BlissInterface/">https://gap-packages.github.io/BlissInterface/</a></span>.
    </p>
    

bibtex: |
    @misc{ BlissInterface0.21,
      author =           {Nagy, G. P.},
      title =            {{BlissInterface},  Low  level  interface  to the bliss
                          graph automorphism tool, {V}ersion 0.21},
      month =            {Oct},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href {https://gap-packages.github.io/BlissInterface/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{BlissInterface/}}},
      printedkey =       {Nag19}
    }

